// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCni4c2ccpO57dOTwFp1w2Ymf1SyxLvYOA',
    appId: '1:823405215452:web:f26d89af8dbdda14e43e19',
    messagingSenderId: '823405215452',
    projectId: 'togetherapp-4560a',
    authDomain: 'togetherapp-4560a.firebaseapp.com',
    storageBucket: 'togetherapp-4560a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgv7gOUyvKBGlvqt2GHLIJJVo9yrKWzvk',
    appId: '1:823405215452:android:e869b57a813b79c3e43e19',
    messagingSenderId: '823405215452',
    projectId: 'togetherapp-4560a',
    storageBucket: 'togetherapp-4560a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1dy7Se_rWpinqBMV9JX2Ub1p-HOf4Yqk',
    appId: '1:823405215452:ios:6f865ecba531bf05e43e19',
    messagingSenderId: '823405215452',
    projectId: 'togetherapp-4560a',
    storageBucket: 'togetherapp-4560a.firebasestorage.app',
    iosBundleId: 'com.example.togetherapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1dy7Se_rWpinqBMV9JX2Ub1p-HOf4Yqk',
    appId: '1:823405215452:ios:6f865ecba531bf05e43e19',
    messagingSenderId: '823405215452',
    projectId: 'togetherapp-4560a',
    storageBucket: 'togetherapp-4560a.firebasestorage.app',
    iosBundleId: 'com.example.togetherapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCni4c2ccpO57dOTwFp1w2Ymf1SyxLvYOA',
    appId: '1:823405215452:web:7da97247e1076a1be43e19',
    messagingSenderId: '823405215452',
    projectId: 'togetherapp-4560a',
    authDomain: 'togetherapp-4560a.firebaseapp.com',
    storageBucket: 'togetherapp-4560a.firebasestorage.app',
  );

}